#!/bin/python

import os
import sys
import subprocess as sh

import apsw, apsw.bestpractice

# initialize apsw
apsw.bestpractice.apply((
	apsw.bestpractice.connection_busy_timeout,
	apsw.bestpractice.connection_enable_foreign_keys,
	apsw.bestpractice.connection_dqs
))


# initialize environment vars
class CFG:
	LABEL_PREFIX	= os.environ.get("CATALIS_LABEL_PREFIX",	"DATA-HMI")
	MOUNTPOINT 		= os.environ.get("CATALIS_MOUNTPOINT",		"/srv/CatalisDATA/")
	DB_SUBDIR 		= os.environ.get("CATALIS_DB_SUBDIR", 		"current/")
	DB_PATTERN 		= os.environ.get("CATALIS_DB_PATTERN", 		"polldata-hmi$HMID")


# create db subdirectory
basepath = os.path.join(CFG.MOUNTPOINT, CFG.DB_SUBDIR)
os.makedirs(basepath, exist_ok=True)

# initialize connection
hmid = sh.getoutput(f"lsblk -o label /dev/{sys.argv[1]} | tail -1").strip(CFG.LABEL_PREFIX)
dbpath =  os.path.join(basepath, (f"{CFG.DB_PATTERN}.sqlite3").replace("$HMID", hmid))
db = apsw.Connection(dbpath)

sh.run(f"echo '(db init) <1/3> Connected to database at {dbpath}'", shell=True)


# initialize polling data packet table
db.execute("""CREATE TABLE IF NOT EXISTS packets (
		   id INTEGER PRIMARY KEY,
		   timestamp TEXT NOT NULL UNIQUE,
		   type TEXT NOT NULL,
		   data TEXT NOT NULL
);""")

sh.run("echo '(db init) <2/3> Initialized \"packets\" table'", shell=True)


# initialize metadata table
db.execute("""CREATE TABLE IF NOT EXISTS meta (
		   id INTEGER PRIMARY KEY,
		   type TEXT NOT NULL UNIQUE,
		   value TEXT
);""")

db.execute("INSERT OR IGNORE INTO meta (type, value) VALUES (?,?)", ("lastsync", "0"))

sh.run("echo '(db init) <3/3> Initialized \"meta\" table'", shell=True)