#!/bin/bash

# start service status indicator service
/bin/systemctl start catalis-led@$1.service
echo "(chmi-init) <1/2> Started service status indicator daemon"

# restart networking (if necessary) to load config file
echo -n "(chmi-init) <2/2> Connecting to wireless network... "
if [ $(wget -q --spider http://google.com ; echo $?) -ne 0 ]; then
	systemctl restart networking
	echo "connected"
else
	echo "already connected"
fi