#!/bin/python

import os
import sys
import subprocess as sh

from CatalisUtils.database import CatalisDB

import apsw, apsw.bestpractice

# initialize apsw
apsw.bestpractice.apply((
	apsw.bestpractice.connection_busy_timeout,
	apsw.bestpractice.connection_enable_foreign_keys,
	apsw.bestpractice.connection_dqs
))


# initialize environment vars
class CFG:
	LABEL_PREFIX	= os.environ.get("CATALIS_LABEL_PREFIX",	"DATA-HMI")
	MOUNTPOINT 		= os.environ.get("CATALIS_MOUNTPOINT",		"/srv/CatalisDATA/")
	DB_SUBDIR 		= os.environ.get("CATALIS_DB_SUBDIR", 		"current/")
	DB_PATTERN 		= os.environ.get("CATALIS_DB_PATTERN", 		"polldata-hmi$HMID")


# create db subdirectory
basepath = os.path.join(CFG.MOUNTPOINT, CFG.DB_SUBDIR)
os.makedirs(basepath, exist_ok=True)

# initialize connection
hmid = sh.getoutput(f"lsblk -o label /dev/{sys.argv[1]} | tail -1").strip(CFG.LABEL_PREFIX)
dbpath =  os.path.join(basepath, (f"{CFG.DB_PATTERN}.sqlite3").replace("$HMID", hmid))
db = CatalisDB(dbpath)

# initialize database
db.initialize()